apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    servicefor: pages
  name: pages-second
spec:
  ports:
    - name: pages-service-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    servicefor: pages
  type: ClusterIP
status:
  loadBalancer: {}
