apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pages
  name: pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
  strategy:
    type: RollingUpdate
      maxSurge: 1

  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pages
    spec:
      containers:
      - image: deepakpesit/pages:latest
        name: pages
        env:
          - name: PAGE_CONTENT
            valueFrom:
              configMapKeyRef: 
                name: pages-config-map
                key: PAGE_CONTENT
        resources: {}
status: {}
