apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pages
  name: pages
spec:
  ports:
  - name: pages-service-port
    port: 8080
    protocol: TCP
    targetPort: 8089
  selector:
    app: pages
    servicefor: pages
  type: ClusterIP
status:
  loadBalancer: {}
