apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pages
  name: pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pages
    spec:
      containers:
      - image: deepakpesit/pages:latest
        name: pages
        env:
          - name: PAGE_CONTENT
            value: "GreenPages coming to a green world!"
        resources: {}
status: {}
