apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app:
    servicefor:
  name:
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
      servicefor:
  template:
    metadata:
      labels:
        app:
        servicefor:
    spec:
      containers:
      - image:
        name:
        ports:
          - containerPort: 8080