apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: pages
  name: pages
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: pages
  type: ClusterIP
status:
  loadBalancer: {}
