apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pages
    servicefor: pages
  name: pages
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pages
      servicefor: pages
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pages
        servicefor: pages
    spec:
      containers:
      - image: deepakpesit/pages:latest
        name: pages
        ports:
          - containerPort: 8080
        env:
          - name: PAGE_CONTENT
            valueFrom:
              configMapKeyRef: 
                name: pages-config-map
                key: PAGE_CONTENT
          - name: SPRING_DATASOURCE_URL
            value: jdbc:mysql://pages-mysql/pages
          - name: SPRING_DATASOURCE_USERNAME
            value: "root"
          - name: SPRING_DATASOURCE_PASSWORD
            value: "password"
        resources: {}
status: {}
