name: Pal Tracker Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        pwd
        chmod +x ./gradlew build
        pwd
        echo $GITHUB_WORKSPACE
        echo '------------------------------------'
        mkdir --parents results/artifacts
        env | grep GITHUB_ | sort > results/artifacts/ci-env.txt
        echo '------------------------------------'

    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: pages
        path: build/libs


  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sathisara/pages
        tags: latest
