name: Pages Pipeline

on:
  push:
    branches: [master]

jobs:
  build-artifact:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Startup test database instance
      run: sudo service mysql start
    - name: Create test database
      run: |
        mysql -uroot -proot < databases/create_database.sql
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: build/libs/pages.jar
  TEST-build-docker-image:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
#    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: artifact
    - name: Display structure of downloaded files
      run: ls -R

  build-docker-image:
    needs: build-artifact
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v2
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: deepakpesit/pages
        tags: latest

