name: Pages Pipeline

on:
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Gradle
      run: |
        chmod +x ./gradlew build
        ls -a
        ls build/libs/ -a
        ls ${{ github.workspace }}
        cp Dockerfile build/libs
  #      cp build/libs/pages.jar ${{ github.workspace }}

    - name: Publish artifact
      uses: actions/upload-artifact@v1
      with:
        name: pages
        path: build/libs


  deploy:
    needs: build-and-publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sathiasara/pages
        tags: latest
